package com.redcare.pharmacy.model

import com.redcare.pharmacy.common.SuperModelInterface

data class GithubRepositoryModel(
    override val id: Int,
    val name: String,
    val fullName: String,
    val description: String?,
    val language: String?,
    val owner: GithubOwnerModel,
    val topics: List<String>,
    val stargazersCount: Int,
    val isPrivate: Boolean,
    val visibility: String,
    val isArchived: Boolean,
    val isDisabled: Boolean,
    val hasIssues: Boolean,
    val hasProjects: Boolean,
    val hasWiki: Boolean,
    val canFork: Boolean,
    val htmlUrl: String,
    val url: String,
    val forksUrl: String,
    val teamsUrl: String,
    val eventsUrl: String,
    val issueEventsUrl: String,
    val issuesUrl: String,
    val cloneUrl: String,
    val isAllowForking: Boolean,
    val defaultBranch: String,
    val createdAt: String,
    val updatedAt: String,
): SuperModelInterface

data class GithubOwnerModel(
    val login: String,
    val id: Int,
    val avatarUrl: String,
    val url: String,
    val htmlUrl: String,
    val followersUrl: String,
    val followingUrl: String,
    val gistsUrl: String,
    val starredUrl: String,
    val subscriptionsUrl: String,
    val organizationsUrl: String,
    val reposUrl: String,
    val eventsUrl: String,
    val receivedEventsUrl: String,
    val type: String,
    val isSiteAdmin: Boolean,
)
